export const SAVEUSERINFO = 'saveuserinfo'
export const DELETEUSERINFO = 'deleteuserinfo'
export const UPDATETITLE = 'updatetitle'
export const UPDATEPRODLIST = 'updateprodlist'
export const SAVECATELIST = 'savecatelist'